openapi: 3.0.0
info:
  title: Clik/ZConnect API
  description: 'TODO: Add a description'
  version: 1.0
servers:
- url: http://www.example.com
  variables: {}
paths:
  /api/v1/acount/{account_guid}/device/{device_guid}/alert:
    post:
      tags:
      - Device Alerts
      summary: New device alert
      description: >-
        When there has been some kind of fault detected with a machine, a new alert can be raised in the ZConnect. This will generate a HTTP request to the Clik servers on this URL to indicate that a fault has been detected.

        The response to one of these requests should indicate if a new or existing job has been linked to this alert and give some relevant information which will aid users of the ZConnect platform in accessing the information in Clik.
      operationId: NewDeviceAlert
      parameters:
      - name: account_guid
        in: path
        description: A GUID string for the user's account on Clik
        required: true
        style: matrix
        explode: false
        schema:
          type: string
        example: a70fcc3a-3ad5-42ed-9b13-dfd1331e97f2
      - name: device_guid
        in: path
        description: A GUID string for the device
        required: true
        style: matrix
        explode: false
        schema:
          type: string
        example: be44724a-dd19-4a92-8066-a4d3f18b66b9
      - name: alert_guid
        in: query
        description: A GUID which is generated for a specific job on a machine
        required: true
        style: matrix
        explode: false
        schema:
          type: string
        example: 76c47b63-a259-4a0c-b4b3-06a702500d58
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertRequest'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertResponse'
        404:
          description: ''
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /api/v1/acount/{account_guid}/device/{device_guid}/alert/{alert_guid}:
    get:
      tags:
      - Device Alerts
      summary: Get device alert
      description: From time-to-time it may be useful to be able to fetch the latest status of an alert, e.g. if an update is to be attempted, it might be worth checking that an engineer is not already on site etc.
      operationId: GetDeviceAlert
      parameters:
      - name: account_guid
        in: path
        description: A GUID string for the user's account on Clik
        required: true
        style: matrix
        explode: false
        schema:
          type: string
        example: a70fcc3a-3ad5-42ed-9b13-dfd1331e97f2
      - name: device_guid
        in: path
        description: A GUID string for the device
        required: true
        style: matrix
        explode: false
        schema:
          type: string
        example: be44724a-dd19-4a92-8066-a4d3f18b66b9
      - name: alert_guid
        in: path
        description: A GUID which is generated for a specific job on a machine
        required: true
        style: matrix
        explode: false
        schema:
          type: string
        example: 76c47b63-a259-4a0c-b4b3-06a702500d58
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertResponse'
        404:
          description: ''
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      tags:
      - Device Alerts
      summary: Update device alert
      description: When ZConnect needs to provide new information for a fault which has developed over time, or the status needs to be changed, an update will be attempted on an existing alert.
      operationId: UpdateDeviceAlert
      parameters:
      - name: account_guid
        in: path
        description: A GUID string for the user's account on Clik
        required: true
        style: matrix
        explode: false
        schema:
          type: string
        example: a70fcc3a-3ad5-42ed-9b13-dfd1331e97f2
      - name: device_guid
        in: path
        description: A GUID string for the device
        required: true
        style: matrix
        explode: false
        schema:
          type: string
        example: be44724a-dd19-4a92-8066-a4d3f18b66b9
      - name: alert_guid
        in: path
        description: A GUID which is generated for a specific job on a machine
        required: true
        style: matrix
        explode: false
        schema:
          type: string
        example: 76c47b63-a259-4a0c-b4b3-06a702500d58
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertRequest'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertResponse'
        423:
          description: ''
        404:
          description: ''
      deprecated: false
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
components:
  schemas:
    Error:
      title: Error
      required:
      - title
      type: object
      properties:
        title:
          type: string
          description: Machine identifiable error code
        description:
          type: string
          description: Human readable error description
    AlertRequest:
      title: AlertRequest
      required:
      - description
      type: object
      properties:
        description:
          type: string
          description: A description which will contain a human readable description, formated as plain text (with new lines etc).
        alert_priority:
          description: A string from a set of options [`emergency`, `warning`, `advisory`, `information`] which indicates how important this alert is
          $ref: '#/components/schemas/AlertPriority'
    AlertPriority:
      title: alert_priority
      enum:
      - emergency
      - warning
      - advisory
      - information
      type: string
    Link:
      title: Link
      type: object
      properties:
        href:
          type: string
          description: A url to open
        title:
          type: string
          description: A suitable title
        rel:
          type: string
          description: A machine identifiable string which contains info about what this link is for, e.g. `ios-app` or `web`.
    AlertResponse:
      title: AlertResponse
      required:
      - alert_guid
      type: object
      properties:
        alert_guid:
          type: string
          description: A reference which ZConnect can use to get the status of this alert/job. It may be easier to make this a job id if a job is always raised.
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
          description: Links for viewing more information about this in Clik
        status:
          type: string
          description: A status to show for this alert/job. tbc
